---
creation_rules:
    # By default allow following keys to encrypt/decrypt secrets
    # Specific path can be configured as explained here
    # https://github.com/mozilla/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files
    # !  The first regex that matches is selected
    - path_regex: cert/pki/private/ca.key.enc
      key_groups:
          - pgp:
                - '56D8342434B84E2D1CCF53D96E9A025D52210D3D'  # Olblak
                - '6699E555C6730CAED9083B7AD40F4AD2F55AF15F'  # timja
                - 'E104B7543ECCCC68EA1EB35DD9B2DBFB59AD8344'  # Markewaite
                - '29B84443F41DE582F71599AFB47082DEE225AE06'  # Damien Duportal
