---
creation_rules:
  # By default allow following keys to encrypt/decrypt secrets
  # Specific path can be configured as explained here
  # https://github.com/mozilla/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files
  # !  The first regex that matches is selected
  - path_regex: cert/pki/private/ca.key.enc
    key_groups:
      - pgp:
        - '6699E555C6730CAED9083B7AD40F4AD2F55AF15F'  # timja
        - 'E104B7543ECCCC68EA1EB35DD9B2DBFB59AD8344'  # Markewaite
        - '29B84443F41DE582F71599AFB47082DEE225AE06'  # Damien Duportal
        - 'EE80BE3F340D4BD5A8F67794D63ECCA17D00EFE6'  # hlemeur
        - 'DDE4B4D6771E87C612ED990D1110C7B1CA22ADE9'  # smerle
        - '88FABF5F307FB5870B6AD2E8A266F2D3F9D60C45'  # Halkeye
