name: Release Drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [released]
# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
        with:
          # This token is generated automatically by default in GitHub Actions: no need to create it manually
          token: ${{ secrets.GITHUB_TOKEN }}
